### ISSUE TITLE
Post-Order Traversal

### ISSUE THREAD

**Issue by tkohlman** [mrjoelkemp/node-dependency-tree#17]
If you change the following code in the traverse function:

```
var tree = [filename];
...
// Prevents redundancy about each memoized step
tree = removeDups(tree);
```
...to the following:

```
var tree = []; // now empty
...
tree = tree.concat(filename); // added

// Prevents redundancy about each memoized step
tree = removeDups(tree);
```

...the resulting list should be the equivalent of a post-order traversal of the dependency tree, with the entry file as the last element in the list. The list would not only give you the set of files in the dependency tree, it would give you the proper concatenation order of the source files when bundling the files as part of a build.

**Comment by mrjoelkemp** [comment]
Thanks for contributing, Tom. I'll look into this tip soon. As per a proper
dependency listing for builds, perhaps an object would be a more
appropriate data structure.

I'd love to get the object form as the default output and have the list
form computed from that as a public method. I'd accept a PR if you're
interested.

Thanks again!

**Comment by tkohlman** [comment]
I'll work on a PR. Thanks!
