### ISSUE TITLE
Support for webpack resolution

### ISSUE THREAD

**Issue by SimenB** [mrjoelkemp/node-dependency-tree#27]
As request in #23, a new issue tracking support for webpack.

Use `stats`? Or just consume the config from webpack?

**Comment by mrjoelkemp** [comment]
Does webpack have an api that lets you give it a module path and a webpack config and it'll tell you the absolute path of that module/file?

**Comment by SimenB** [comment]
As far as I know there isn't. I think you have to print out the build information afterwards. But @sokra probably knows. Or you can ask on Gitter? https://gitter.im/webpack/webpack

**Comment by sokra** [comment]
webpack's resolve is powered by https://github.com/webpack/enhanced-resolve

**Comment by mrjoelkemp** [comment]
Thanks Tobias! Appreciate the help.

**Comment by mrjoelkemp** [comment]
@SimenB Webpack support has landed! I used the awesome enhanced-resolve module that Sokra linked to.

I just cut a minor release. Please let me know if you have any issues.
