### ISSUE TITLE
cli name conflicting with the popular tree

### ISSUE THREAD

**Issue by NKjoep** [mrjoelkemp/node-dependency-tree#30]
Hello,

please consider to rename the cli executable name, since `tree` is a common utility in linux.

```log
09:38 $  tree --version
tree v1.7.0 (c) 1996 - 2014 by Steve Baker, Thomas Moore, Francesc Rocher, Florian Sesser, Kyosuke Tokoro
```

**Comment by mrjoelkemp** [comment]
Thanks for the heads up! I can change it to dependency-tree and cut a major
version. I'm out of the country, so the release would have to wait for a
few weeks.

Would you like to submit a PR with the change to the package.json and
readme?

Thanks,
Joel

**Comment by mrjoelkemp** [comment]
Fixed via https://github.com/mrjoelkemp/node-dependency-tree/pull/31
